name: Build and Deploy WebGL

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

jobs:
  build:
    name: Build for WebGL âœ¨
    runs-on: ubuntu-latest
    steps:
    # --- Reclaim disk space ---
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # This frees up ~15-20GB by removing Android, .NET, and Haskell
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      # Checkout the code (including LFS files)
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache the Library folder to speed up future builds
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-

      # Build the Unity Project
      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Deploy the 'build/WebGL/WebGL' folder to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL/WebGL